services:
  # Crypto 01
  crypto01:
    build: ./crypto01/src
    #ports:
    #  - "8000:8000"
    privileged: false
    restart: unless-stopped
    environment:
      - FLAG=flag{T0o_3a$$y_f0r_Cyb3rCh3f} # Il $ in più serve per renderlo come un carattere e non una variabile
      - FLASK_ENV=production
      - FLASK_APP=app
      - GUNICORN_WORKERS # default: 4
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.crypto01.entrypoints=web"
      - "traefik.http.routers.crypto01.rule=Host(`rotten-lottery.challs.olicyber.it`)"
      - "traefik.http.services.crypto01.loadbalancer.server.port=8000"
    networks:
      - web

  # Crypto 02
  crypto02:
    build: ./crypto02/src
    #ports:
    #  - "8000:8000"
    environment:
      - FLAG=flag{S3ed_1s_N0t_5o_R4nd0m_4f7eR_A11!}
      - FLASK_ENV=production
      - FLASK_APP=app
      - GUNICORN_WORKERS # default: 4
    privileged: false
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.crypto02.entrypoints=web"
      - "traefik.http.routers.crypto02.rule=Host(`seeded-lottery.challs.olicyber.it`)"
      - "traefik.http.services.crypto02.loadbalancer.server.port=8000"
    networks:
      - web

  # Crypto 03
  crypto03:
    build: ./crypto03/src
    #ports:
    #  - "8000:8000"
    environment:
      - FLAG=flag{Y0uR_f1rs7_Ch0s3n_Pl4in73x7_4ttAcK}
      - FLASK_ENV=production
      - FLASK_APP=app
      - GUNICORN_WORKERS # default: 4
    privileged: false
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.crypto03.entrypoints=web"
      - "traefik.http.routers.crypto03.rule=Host(`oracle-name.challs.olicyber.it`)"
      - "traefik.http.services.crypto03.loadbalancer.server.port=8000"
    networks:
      - web

  # Crypto 04
  crypto04:
    build: ./crypto04/src
    #ports:
    #  - "8000:8000"
    environment:
      - FLAG=flag{H4rry_P0tt3r_4nd_7h3_X0R_st0n3}
      - XOR_KEY=Qu1dd1tcH
      - FLASK_ENV=production
      - FLASK_APP=app
      - GUNICORN_WORKERS # default: 4
    privileged: false
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.crypto04.entrypoints=web"
      - "traefik.http.routers.crypto04.rule=Host(`xor.challs.olicyber.it`)"
      - "traefik.http.services.crypto04.loadbalancer.server.port=8000"
    networks:
      - web

  # Crypto 05
  crypto05:
    build: ./crypto05/src
    #ports:
    #  - "8000:8000"
    environment:
      - FLAG=flag{s0_Y0u_4r3_4_b1t_fl1pp3R}
      - FLASK_ENV=development
      - FLASK_APP=app
      - FLASK_SECRET_KEY=LD4bbOsePhMr4VW8pw25cCUtcBOrRPFw
      - GUNICORN_WORKERS # default: 4
    privileged: false
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.crypto05.entrypoints=web"
      - "traefik.http.routers.crypto05.rule=Host(`flipper-equation.challs.olicyber.it`)"
      - "traefik.http.services.crypto05.loadbalancer.server.port=8000"
    networks:
      - web

  # Crypto 06
  crypto06:
    build: ./crypto06/src
    #ports:
    #  - "8000:8000"
    environment:
      - FLAG=flag{D1ff13_H3llm4nn_K3y_3xch4ng3_4lg0r1thm}
      - FLASK_ENV=production
      - FLASK_APP=app
      - GUNICORN_WORKERS # default: 4
    privileged: false
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.crypto06.entrypoints=web"
      - "traefik.http.routers.crypto06.rule=Host(`dhke.challs.olicyber.it`)"
      - "traefik.http.services.crypto06.loadbalancer.server.port=8000"
    networks:
      - web

  # Web 01
  web01:
    build: ./web01/src
    environment:
      - "FLAG=flag{Non_ho_voglia_di_studiar3}"
    #ports:
    #  - "80:80"
    privileged: false
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.web01.entrypoints=web"
      - "traefik.http.routers.web01.rule=Host(`trova-le-soluzioni.challs.olicyber.it`)"
      - "traefik.http.services.web01.loadbalancer.server.port=80"
    networks:
      - web

  # Web 02
  web02:
    build: ./web02/src
    environment:
      - "FLAG=flag{i0_n0n_stud13r0_m41!}"
    #ports:
    #  - "80:80"
    privileged: false
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.web02.entrypoints=web"
      - "traefik.http.routers.web02.rule=Host(`trova-le-soluzioni-2.challs.olicyber.it`)"
      - "traefik.http.services.web02.loadbalancer.server.port=80"
    networks:
      - web

  # Web 03
  web03:
    build:
      context: ./web03/src
      dockerfile: Dockerfile
      args:
        - "MYSQL_HOST=web03-db"
        - "MYSQL_DATABASE=soluzioni"
        - "MYSQL_USER=soluzioni"
        - "MYSQL_PASSWORD=msZ,myzAaSid+LCGx70r"
    environment:
      - "FLAG=flag{SQL_inj3ction_se3ms_4m4z1ng}"
    #ports:
    #  - "80:80"
    privileged: false
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.web03.entrypoints=web"
      - "traefik.http.routers.web03.rule=Host(`trova-le-soluzioni-3.challs.olicyber.it`)"
      - "traefik.http.services.web03.loadbalancer.server.port=80"
    depends_on:
      web03-db:
        condition: service_healthy
    networks:
      - web
      - default

  web03-db:
    image: mysql:8.0.35
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      - "MYSQL_ROOT_PASSWORD=1IYaQX-CO8ggaZ^o8GpL."
      - "MYSQL_DATABASE=soluzioni"
      - "MYSQL_USER=soluzioni"
      - "MYSQL_PASSWORD=msZ,myzAaSid+LCGx70r"
    volumes:
      - ./web03/src/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    networks:
      - default

  # Web 04
  web04:
    build: ./web04/src
    environment:
      - "FLAG=flag{R3mote_c0de_3x3cution_vuln3r4b1l1ty_1s_4lw4ys_d4ng3r0us}"
    #ports:
    #  - "80:80"
    privileged: false
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.web04.entrypoints=web"
      - "traefik.http.routers.web04.rule=Host(`calcolatrice.challs.olicyber.it`)"
      - "traefik.http.services.web04.loadbalancer.server.port=80"
    networks:
      - web

  # Web 05
  web05:
    build: ./web05/src
    environment:
      - "FLAG=flag{A_R4ce_c0nd1t10n_in_a_trading_system!?}"
      - "MYSQL_HOST=web05-db"
      - "MYSQL_DATABASE=trading"
      - "MYSQL_USER=trading"
      - "MYSQL_PASSWORD=mha-qAx0,NXyijwzr.B3e"
    #ports:
    #  - "80:80"
    volumes:
      - ./web05/src/app/public/index.php:/usr/local/apache2/htdocs/public/index.php
    privileged: false
    depends_on:
      web05-db:
        condition: service_healthy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.web05.entrypoints=web"
      - "traefik.http.routers.web05.rule=Host(`trading.challs.olicyber.it`)"
      - "traefik.http.services.web05.loadbalancer.server.port=80"
    networks:
      - web
      - default

  web05-db:
    image: mysql:8.0.35
    privileged: false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      - "MYSQL_ROOT_PASSWORD=XK/p27+nHLRYnpff9KMXf7"
      - "MYSQL_DATABASE=trading"
      - "MYSQL_USER=trading"
      - "MYSQL_PASSWORD=mha-qAx0,NXyijwzr.B3e"
    volumes:
      - ./web05/src/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    networks:
      - default

  # Web 06
  web06:
    build: ./web06/src
    environment:
      - "FLAG=flag{SSRF_this_CRLF_that_vulns_everywhere}"
    #ports:
    #  - "80:80"
    privileged: false
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.web06.entrypoints=web"
      - "traefik.http.routers.web06.rule=Host(`the-backend.challs.olicyber.it`)"
      - "traefik.http.services.web06.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    external: true
