version: "3"

services:
  web04:
    build: .
    environment:
      - "FLAG=flag{R3mote_c0de_3x3cution_vuln3r4b1l1ty_1s_4lw4ys_d4ng3r0us}"
    ports:
      - "80:80"
    privileged: false
    restart: unless-stopped
